name: Deploy Alcamala to Github Pages

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout [main] branch
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish .NET Core Project
      run: dotnet publish ./Alcamala/Alcamala.csproj -c:Release -p:GHPages=true -o release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: gh-pages
        FOLDER: release/wwwroot
