name: Deploy Alcamala to Github Pages

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy-to-github-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout [main] branch
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish .NET Core Project
      run: dotnet publish ./Alcamala/Alcamala.csproj -c:Release -p:GHPages=true -o release --nologo

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
      with:
        html_path: release/wwwroot/index.html
        base_href: /Alcamala/

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./release/wwwroot
